"""create tasks table

Revision ID: 3d668ae16d57
Revises: f889b14d2615
Create Date: 2026-07-22 20:26:32.230766

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d668ae16d57'
down_revision: Union[str, Sequence[str], None] = 'f889b14d2615'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('estimated_pomodoros', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('completed_pomodoros', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('is_completed', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('\n            (\n                is_completed = false\n                AND completed_at IS NULL\n            )\n            OR\n            (\n                is_completed = true\n                AND completed_at IS NOT NULL\n            )\n            ', name='ck_tasks_completion_state'),
    sa.CheckConstraint('completed_pomodoros >= 0', name='ck_tasks_completed_pomodoros_non_negative'),
    sa.CheckConstraint('estimated_pomodoros >= 0', name='ck_tasks_estimated_pomodoros_non_negative'),
    sa.CheckConstraint('length(btrim(title)) > 0', name='ck_tasks_title_not_blank'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_tasks_user_id_users', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_tasks_user_id_created_at', 'tasks', ['user_id', 'created_at'], unique=False)
    op.create_index('ix_tasks_user_id_is_completed', 'tasks', ['user_id', 'is_completed'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_tasks_user_id_is_completed', table_name='tasks')
    op.drop_index('ix_tasks_user_id_created_at', table_name='tasks')
    op.drop_table('tasks')
    # ### end Alembic commands ###
