"""create focus sessions table

Revision ID: a18f2746e2b6
Revises: 3d668ae16d57
Create Date: 2026-07-22 21:41:28.826508

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a18f2746e2b6'
down_revision: Union[str, Sequence[str], None] = '3d668ae16d57'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('focus_sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('session_type', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'started'"), nullable=False),
    sa.Column('planned_duration_seconds', sa.Integer(), nullable=False),
    sa.Column('actual_duration_seconds', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("\n            (\n                status = 'started'\n                AND ended_at IS NULL\n                AND actual_duration_seconds IS NULL\n            )\n            OR\n            (\n                status IN (\n                    'completed',\n                    'cancelled',\n                    'interrupted'\n                )\n                AND ended_at IS NOT NULL\n                AND actual_duration_seconds IS NOT NULL\n            )\n            ", name='ck_focus_sessions_lifecycle_fields'),
    sa.CheckConstraint("\n            session_type IN (\n                'focus',\n                'short_break',\n                'long_break'\n            )\n            ", name='ck_focus_sessions_session_type'),
    sa.CheckConstraint("\n            status IN (\n                'started',\n                'completed',\n                'cancelled',\n                'interrupted'\n            )\n            ", name='ck_focus_sessions_status'),
    sa.CheckConstraint("\n            task_id IS NULL\n            OR session_type = 'focus'\n            ", name='ck_focus_sessions_task_only_for_focus'),
    sa.CheckConstraint('\n            actual_duration_seconds IS NULL\n            OR actual_duration_seconds >= 0\n            ', name='ck_focus_sessions_actual_duration_non_negative'),
    sa.CheckConstraint('\n            ended_at IS NULL\n            OR ended_at >= started_at\n            ', name='ck_focus_sessions_end_after_start'),
    sa.CheckConstraint('planned_duration_seconds > 0', name='ck_focus_sessions_planned_duration_positive'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], name='fk_focus_sessions_task_id_tasks', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_focus_sessions_user_id_users', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_focus_sessions_task_id_started_at', 'focus_sessions', ['task_id', 'started_at'], unique=False)
    op.create_index('ix_focus_sessions_user_id_started_at', 'focus_sessions', ['user_id', 'started_at'], unique=False)
    op.create_index('ix_focus_sessions_user_id_status', 'focus_sessions', ['user_id', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_focus_sessions_user_id_status', table_name='focus_sessions')
    op.drop_index('ix_focus_sessions_user_id_started_at', table_name='focus_sessions')
    op.drop_index('ix_focus_sessions_task_id_started_at', table_name='focus_sessions')
    op.drop_table('focus_sessions')
    # ### end Alembic commands ###
