"""create user settings table

Revision ID: c768c023f7a3
Revises: 9d84c3bde977
Create Date: 2026-07-23 13:49:03.994595

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c768c023f7a3'
down_revision: Union[str, Sequence[str], None] = "9d84c3bde977"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_settings',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('focus_duration_minutes', sa.Integer(), server_default=sa.text('25'), nullable=False),
    sa.Column('short_break_minutes', sa.Integer(), server_default=sa.text('5'), nullable=False),
    sa.Column('long_break_minutes', sa.Integer(), server_default=sa.text('15'), nullable=False),
    sa.Column('long_break_interval', sa.Integer(), server_default=sa.text('4'), nullable=False),
    sa.Column('auto_start_break', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('auto_start_focus', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('sound_enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('vibration_enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('\n            focus_duration_minutes\n            BETWEEN 1 AND 180\n            ', name='ck_user_settings_focus_duration_range'),
    sa.CheckConstraint('\n            long_break_interval\n            BETWEEN 1 AND 12\n            ', name='ck_user_settings_long_break_interval_range'),
    sa.CheckConstraint('\n            long_break_minutes\n            BETWEEN 1 AND 120\n            ', name='ck_user_settings_long_break_range'),
    sa.CheckConstraint('\n            short_break_minutes\n            BETWEEN 1 AND 60\n            ', name='ck_user_settings_short_break_range'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_user_settings_user_id_users', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_settings')
    # ### end Alembic commands ###
