"""create auth sessions table

Revision ID: f889b14d2615
Revises: b847114b5c7e
Create Date: 2026-07-14 22:21:58.219608

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f889b14d2615'
down_revision: Union[str, Sequence[str], None] = 'b847114b5c7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('refresh_token_hash', sa.String(length=64), nullable=False),
    sa.Column('token_family_id', sa.Uuid(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('replaced_by_session_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.CheckConstraint('expires_at > created_at', name='ck_auth_sessions_expires_after_creation'),
    sa.CheckConstraint('replaced_by_session_id IS NULL OR revoked_at IS NOT NULL', name='ck_auth_sessions_replacement_requires_revocation'),
    sa.CheckConstraint('revoked_at IS NULL OR revoked_at >= created_at', name='ck_auth_sessions_revoked_after_creation'),
    sa.ForeignKeyConstraint(['replaced_by_session_id'], ['auth_sessions.id'], name='fk_auth_sessions_replaced_by_auth_sessions', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_auth_sessions_user_id_users', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('refresh_token_hash', name='uq_auth_sessions_refresh_token_hash')
    )
    op.create_index('ix_auth_sessions_expires_at', 'auth_sessions', ['expires_at'], unique=False)
    op.create_index('ix_auth_sessions_replaced_by_session_id', 'auth_sessions', ['replaced_by_session_id'], unique=False)
    op.create_index('ix_auth_sessions_token_family_id_revoked_at', 'auth_sessions', ['token_family_id', 'revoked_at'], unique=False)
    op.create_index('ix_auth_sessions_user_id_revoked_at', 'auth_sessions', ['user_id', 'revoked_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_auth_sessions_user_id_revoked_at', table_name='auth_sessions')
    op.drop_index('ix_auth_sessions_token_family_id_revoked_at', table_name='auth_sessions')
    op.drop_index('ix_auth_sessions_replaced_by_session_id', table_name='auth_sessions')
    op.drop_index('ix_auth_sessions_expires_at', table_name='auth_sessions')
    op.drop_table('auth_sessions')
    # ### end Alembic commands ###
